### ISSUE TITLE
derive_var_trtsdtm - user feedback

### ISSUE THREAD

**Issue by aehmann-gsk** [Roche-GSK/admiral#437]
In the adsl workflow (https://roche-gsk.github.io/admiral/articles/adsl.html) derive_var_trtsdtm appends a time_stamp of 00:00 this shows in the console but not in the dataset. Albeit benign is this designed?

https://myteams.gsk.com/_api/v2.1/drives/b!FNNldQ__A0WRKCVMrqgAMmTBDGe-709BnN0VCBVHDh9cL86DlG5iR5vuDeaZN8ay/items/01V5Q7RQEFQAQHLRLPKRCIVTNTCPLL4DJ5/thumbnails/0/c3000x2000/content?prefer=noredirect%2Cclosestavailablesize&cb=1&s=L3NpdGVzL0FkbWlyYWwvTGlzdHMvYWRtaXJhbCBJc3N1ZSB0cmFja2VyfEltYWdlc3wxMA

**Comment by teckla-gsk** [comment]
@kabis-ops the comment you provided seems to discuss a different issue. I thought this issue was on the date not fully being printed in the dataset when it's midnight. I might be missing something here

**Comment by kabis-ops** [comment]
Hi @teckla-gsk, you are right these are different issues but they are all related to the user feedback on `derive_var_trtsdtm`: that's why it is included here.
The midnight issue is now corrected (thought we may still have this issue with time zone), but the documentation of the function should be updated as per the 1st bullet. 
And regarding the 2nd bullet, I guess we need to discuss whether we should impute partial dates by default in the function even if the `filter` parameter provides options to filter on complete dates?
@bundfussr , @aehmann-gsk , @thomas-neitmann - what do you think?

The `derive_var_trtedtm` will need to be updated in the same way.

**Comment by bundfussr** [comment]
I think we should add parameters (`date_imputation` and `time_imputation`) to specify the imputation. Then it is clear from the call whether imputation is done or not. I am not sure which default we should use. Maybe no default?

There are more issue regarding these functions:
- If imputation is done, the imputation flags need to be added as well. (We need to rename the functions then.)
- In `derive_var_trtedtm()` the imputation must be done before the last observation is selected.
- The default for `filter_ex` is Roche specific. Should we provide no default value to force the user to think about it?

**Comment by teckla-gsk** [comment]
From Questions and Comments discussion on Dec 13th, 2021 - this functionality can be incorporated in the enhancement of derive_var_lstalvdt to be derive_var_extreme_dt(m)
